### ISSUE TITLE
[Provider Audit]: provider.yohancloud.eu

### ISSUE THREAD

**Issue by ysestrimski** [akash-network/community#1003]
### 1. Make sure your provider has community provider attributes and your contact details (email, website):

```
  Example:
  $ provider-services query provider get akash1<REDACTED> -o text
  ...
  attributes:
  ...
  - key: host
  value: akash
  - key: tier
  value: community
  info:
    email: "<yohan_s@live.com>"
    website: "<yohancloud.eu>"

```

[Ref documentation:](https://akash.network/docs/providers/audited-attributes/#attribute-auditors).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host provider.ingress.yohancloud.eu
provider.ingress.yohancloud.eu has address 77.85.12.177
```

- More info on what DNS records should look like are available in the [Akash Documentation here](https://akash.network/docs/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/#step-5---domain-name-review).

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
- If you are using a firewall, please follow this doc:
https://akash.network/docs/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/#step-11---firewall-rule-review
- If you are behind NAT, then you need to make sure these ports are open between your provider worker nodes and the internet.

# Audit Steps:

## Leave contact information (optional)
1. Name: Yohan Sestrimski
2. Discord handle: yohan06316
3. Contact email address: yohan_s@live.com

**Comment by shimpa1** [comment]
hi @ysestrimski ,

This is the status of the audit process:
Provider address: akash17yu2t83ghhvp99qml463fns9fs7lxyswly9h0u
Provider URI: provider.yohancloud.eu
Provider URI name resolution works? yes
Ingress URI name resolution works? yes
Provider status endpoint works? yes
Provider grpc status endpoint works? yes
Provider responding to orders? yes
Deployment works? yes
Ingress works? NO
NodePort works? yes
Network functional? n/a
Attributes OK? yes

Your ingress seems to have a load balancer in front of it. the result is that none of the deployments can be reached from the public network.
Other than this, I see no other issue.
Please check the ingress configuration and let us know.

thanks

<img width="1140" height="440" alt="Image" src="https://github.com/user-attachments/assets/7b921f9a-bfef-4d8d-a2b2-93e6172a9d9e" />

**Comment by ysestrimski** [comment]
this the output when I try now:

curl -vk https://provider.ingress.yohancloud.eu/status
* Host provider.ingress.yohancloud.eu:443 was resolved.
* IPv6: (none)
* IPv4: 77.85.12.177
*   Trying 77.85.12.177:443...
* Connected to provider.ingress.yohancloud.eu (77.85.12.177) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=provider.ingress.yohancloud.eu
*  start date: Aug 20 19:47:24 2025 GMT
*  expire date: Nov 18 19:47:23 2025 GMT
*  issuer: C=US; O=Let's Encrypt; CN=E8
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
*   Certificate level 0: Public key type EC/secp384r1 (384/192 Bits/secBits), signed using ecdsa-with-SHA384
*   Certificate level 1: Public key type EC/secp384r1 (384/192 Bits/secBits), signed using sha256WithRSAEncryption
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://provider.ingress.yohancloud.eu/status
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: provider.ingress.yohancloud.eu]
* [HTTP/2] [1] [:path: /status]
* [HTTP/2] [1] [user-agent: curl/8.5.0]
* [HTTP/2] [1] [accept: */*]
> GET /status HTTP/2
> Host: provider.ingress.yohancloud.eu
> User-Agent: curl/8.5.0
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 200
< server: openresty
< date: Thu, 21 Aug 2025 08:13:15 GMT
< content-type: application/json; charset=UTF-8
< content-length: 497
< strict-transport-security: max-age=63072000; preload
< x-served-by: provider.ingress.yohancloud.eu
<
* Connection #0 to host provider.ingress.yohancloud.eu left intact
{"cluster":{"leases":1,"inventory":{"active":[{"cpu":1000,"gpu":0,"memory":536870912,"storage_ephemeral":1073741824}],"available":{"nodes":[{"name":"node1","allocatable":{"cpu":7400,"gpu":0,"memory":43258261504,"storage_ephemeral":93531759255},"available":{"cpu":3850,"gpu":0,"memory":41536425984,"storage_ephemeral":92458017431}}]}}},"bidengine":{"orders":0},"manifest":{"deployments":1},"cluster_public_hostname":"provider.yohancloud.eu","address":"akash17yu2t83ghhvp99qml463fns9fs7lxyswly9h0u"}

**Comment by shimpa1** [comment]
It's still the same.
Visit this [link](http://7lis3i21m19637kdbf18d68lqs.ingress.yohancloud.eu/) - that's my deployment

**Comment by ysestrimski** [comment]
I have added the *.ingress.yohancloud.eu to my nginx proxy manager

<img width="1180" height="70" alt="Image" src="https://github.com/user-attachments/assets/ff03ffbe-172c-45bf-876d-c9d7a18e75d8" />

and now your page is returning 
404 page not found
is this expected or something else is wrong now

**Comment by ysestrimski** [comment]
I do not have much experience but did you deploy the speedtest-tracker svc, if yes from what I can see it is only accessible internally

get svc -n ava219nhk3nfrsn88jaqjgjsum3dujiql4fhk4eicd7n8
NAME                TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
speedtest-tracker   ClusterIP   10.233.5.19   <none>        80/TCP    3h

if you want we debug the problem on discord?

**Comment by ysestrimski** [comment]
Hi, @shimpa1, when will be good for you to discus this on Discord?

**Comment by shimpa1** [comment]
@ysestrimski ,
I've revisited this request and it seems your provider is no longer online.

**Comment by shimpa1** [comment]
closed due to inactivity
